/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateWorkspaceRouteImport } from './routes/_app.create-workspace'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/_app.projects.$projectId.tasks'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app.projects.$projectId.settings'
import { Route as AppProjectsProjectIdCalendarRouteImport } from './routes/_app.projects.$projectId.calendar'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './routes/_app.projects.$projectId.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateWorkspaceRoute = AppCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdCalendarRoute =
  AppProjectsProjectIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-workspace': typeof AppCreateWorkspaceRoute
  '/dashboard': typeof AppDashboardRoute
  '/team': typeof AppTeamRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-workspace': typeof AppCreateWorkspaceRoute
  '/dashboard': typeof AppDashboardRoute
  '/team': typeof AppTeamRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/create-workspace': typeof AppCreateWorkspaceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/team': typeof AppTeamRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/_app/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-workspace'
    | '/dashboard'
    | '/team'
    | '/login'
    | '/register'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-workspace'
    | '/dashboard'
    | '/team'
    | '/login'
    | '/register'
    | '/projects'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/create-workspace'
    | '/_app/dashboard'
    | '/_app/team'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/projects/$projectId'
    | '/_app/projects/'
    | '/_app/projects/$projectId/analytics'
    | '/_app/projects/$projectId/calendar'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/tasks'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-workspace': {
      id: '/_app/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof AppCreateWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks': {
      id: '/_app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/calendar': {
      id: '/_app/projects/$projectId/calendar'
      path: '/calendar'
      fullPath: '/projects/$projectId/calendar'
      preLoaderRoute: typeof AppProjectsProjectIdCalendarRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/analytics': {
      id: '/_app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdCalendarRoute: typeof AppProjectsProjectIdCalendarRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
  AppProjectsProjectIdCalendarRoute: AppProjectsProjectIdCalendarRoute,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppCreateWorkspaceRoute: typeof AppCreateWorkspaceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppTeamRoute: typeof AppTeamRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateWorkspaceRoute: AppCreateWorkspaceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppTeamRoute: AppTeamRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
